const router = require('express').Router()
const dashboardRoutes = require('./dashboard.route')
const accountRoutes = require('./account.route')
const categoryRoutes = require('./category.route')
const orderRoutes = require('./order.route')
const profileRoutes = require('./profile.route')
const settingRoutes = require('./setting.route')
const tourRoutes = require('./tour.route')
const userRoutes = require('./user.route')
const contactRoutes = require('./contact.route')
const auth = require('../../middleware/admin/auth.middleware')

router.use('/account', accountRoutes)
router.use('/dashboard',  auth.verifyToken, dashboardRoutes)
router.use('/category',  auth.verifyToken, categoryRoutes)
router.use('/order', auth.verifyToken, orderRoutes)
router.use('/profile',  auth.verifyToken, profileRoutes)
router.use('/setting',  auth.verifyToken,  settingRoutes)
router.use('/tour',  auth.verifyToken, tourRoutes)
router.use('/user',  auth.verifyToken, userRoutes)
router.use('/contact',  auth.verifyToken, contactRoutes)

module.exports = router