const router = require('express').Router()
const dashboardRoutes = require('./dashboard.route')
const accountRoutes = require('./account.route')
const categoryRoutes = require('./category.route')
const orderRoutes = require('./order.route')
const profileRoutes = require('./profile.route')
const settingRoutes = require('./setting.route')
const tourRoutes = require('./tour.route')
const userRoutes = require('./user.route')
const contactRoutes = require('./contact.route')

router.use('/account', accountRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/category', categoryRoutes)
router.use('/order', orderRoutes)
router.use('/profile', profileRoutes)
router.use('/setting', settingRoutes)
router.use('/tour', tourRoutes)
router.use('/user', userRoutes)
router.use('/contact', contactRoutes)

module.exports = router