const router = require('express').Router()
const dashboardRoutes = require('./dashboard.route')
const accountRoutes = require('./account.route')
const categoryRoutes = require('./category.route')
const orderRoutes = require('./order.route')
const profileRoutes = require('./profile.route')
const settingRoutes = require('./setting.route')
const tourRoutes = require('./tour.route')
const userRoutes = require('./user.route')
const contactRoutes = require('./contact.route')
const uploadRoutes = require('./upload.route')
const messagesRoutes = require('./message.route')
const articleRoutes = require('./article.route')
const discountRoutes = require('./discount.route')
const auth = require('../../middleware/admin/auth.middleware')

router.use('/account', accountRoutes)
router.use('/dashboard',  auth.verifyToken, auth.roleAuth, dashboardRoutes)
router.use('/category',  auth.verifyToken, auth.roleAuth,categoryRoutes)
router.use('/order', auth.verifyToken, auth.roleAuth,orderRoutes)
router.use('/profile',  auth.verifyToken,auth.roleAuth, profileRoutes)
router.use('/setting',  auth.verifyToken, auth.roleAuth, settingRoutes)
router.use('/tour',  auth.verifyToken,auth.roleAuth, tourRoutes)
// router.use('/user',  auth.verifyToken,auth.roleAuth, userRoutes)
router.use('/contact',  auth.verifyToken, auth.roleAuth,contactRoutes)
router.use('/upload', auth.verifyToken,auth.roleAuth, uploadRoutes)
router.use('/messages', auth.verifyToken,auth.roleAuth, messagesRoutes)
router.use('/article', auth.verifyToken,auth.roleAuth, articleRoutes)
router.use('/discount', auth.verifyToken,auth.roleAuth, discountRoutes)
module.exports = router